
replicaCount: 1

env:
- name: DT_ONEAGENT_PREFIX_DIR
  value: /tmp
- name: DT_ONEAGENT_FOR
  value: all
- name: DT_AGENT_BITNESS
  value: "64"
- name: TZ
  value: Etc/UTC
- name: ENVIRONMENT
  value: ppd1
- name: DT_NODE_ID
  value: ppd1
- name: DT_CLUSTER_ID
  value: nodetest
- name: JASYPT_PASSWORD
  value: JENKINS_INJECTED_JASYPT_PASSWORD
- name: DT_TENANT
  value: ell97466
- name: DT_API_TOKEN
  value: KnMuWwkOQMChcBVnjKmFO


ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: alb,
    alb.ingress.kubernetes.io/backend-protocol: HTTP,
    alb.ingress.kubernetes.io/target-type: ip,
    alb.ingress.kubernetes.io/scheme: internal,
    alb.ingress.kubernetes.io/group.name: ppd1-oth,
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]',
#    alb.ingress.kubernetes.io/healthcheck-path: /health,
#    alb.ingress.kubernetes.io/healthcheck-port: health,
#    alb.ingress.kubernetes.io/success-codes: '200',
    alb.ingress.kubernetes.io/security-groups: 'eks-alb-ppd1-sg',
    alb.ingress.kubernetes.io/tags: "Environment=ppd1,alb-group=ppd1-oth"
  }
  hosts:
    - host: overwritten.by.jenkins
  tls: []

inmCostAllocationApplication: Fargate
inmCostAllocationProduct: IntegrationPlatform
inmCostAllocationCostCentre: 5162
