apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "#TEMPLATE_NAME#.fullname" . }}
  labels:
    {{- include "#TEMPLATE_NAME#.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "#TEMPLATE_NAME#.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "#TEMPLATE_NAME#.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "#TEMPLATE_NAME#.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
              {{- /*  Uncomment this section to re-add health probe
            - name: health
              containerPort: 8778
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.health.timeoutSeconds }}
            periodSeconds: {{ .Values.health.periodSeconds }}
            failureThreshold: {{ .Values.health.failureThreshold }}
            successThreshold: {{ .Values.health.successThreshold }}
            */}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/configmap
            name: #TEMPLATE_NAME#-config
            readOnly: true
          - mountPath: /etc/secret
            name: #TEMPLATE_NAME#-secret
            readOnly: true
      volumes:
        - name: #TEMPLATE_NAME#-config
          configMap:
            name: #TEMPLATE_NAME#
        - name: #TEMPLATE_NAME#-secret
          secret:
            secretName: #TEMPLATE_NAME#
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
