apiVersion: v1
kind: Secret
metadata:
  name: nodetest
  labels:
    {{- include "nodetest.labels" . | nindent 4 }}
type: Opaque
data:
  "app.secret": |-
    {{ .Files.Get "secret/app.secret" | b64enc }}
