apiVersion: v1
kind: Secret
metadata:
  name: #TEMPLATE_NAME#
  labels:
    {{- include "#TEMPLATE_NAME#.labels" . | nindent 4 }}
type: Opaque
data:
  "app.secret": |-
    {{ .Files.Get "secret/app.secret" | b64enc }}
